# Generated by Django 3.2.20 on 2023-08-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatavabilty',
            old_name='user_pencard',
            new_name='user_pancard',
        ),
    ]
