# Generated by Django 3.2.20 on 2023-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0002_rename_user_pencard_seatavabilty_user_pancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartment',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='seatavabilty',
            name='seat_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatavabilty',
            name='status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('Open', 'Open'), ('Waiting', 'Waiting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seatavabilty',
            name='user_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatavabilty',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seatavabilty',
            name='user_pancard',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
