# Generated by Django 3.2.20 on 2023-08-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_app', '0003_auto_20230809_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatavabilty',
            name='seat_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
